# This is a basic workflow to help you get started with Actions

name: Poll Games

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: 0/15 * * * *

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  play-games:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Run website bot script
        run: |
          sudo apt update && sudo apt install -y python3 python3-pydantic
          sed -i 's/UPDATE_PLAYER_ID/${{ secrets.PLAYER_ID }}/' website_bot.py
          sed -i 's/UPDATE_DEVICEID/${{ secrets.DEV_ID }}/' website_bot.py
          sed -i 's/UPDATE_USEREMAIL/${{ secrets.GINSENG_EM }}/' website_bot.py
          sed -i 's/UPDATE_USERNAME/GinsengBot/' website_bot.py
          python3 website_bot.py